### PR TITLE
Add blockly typings

### PR DESCRIPTION
**Pull request by NCC1701M**
Added `blockly.ts` from https://github.com/google/blockly/tree/master/typings directly because using `import * as Blockly from "blockly"` doesn't work very well for languages. So I "imported" blockly.ts with the [triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) instead.

For variables, etc. which are not directly within blockly.d.ts I added `blockly.extended.ts`.

Both files are referenced within `public_api.ts` and will be added to the build output.

I also removed all `declare var Blockly: any` definitions in favour of the Blockly module.

As described in https://github.com/google/blockly/tree/master/typings we can
> can include a copy of this file with your sources

### CODE REVIEW

**Comment by roroettg** [comment]
Thank you very much for your PR. 

Sorry that it did take so long for me reviewing it, but I was pretty busy the last weeks. Since we were refactoring ngx-blockly to make use of the blockly npm package your changes came in pretty handy.

I have used many of your ideas and worked them in the master branch. Since the refactoring is not done, I published a RC with following version 10.2.0-RC-1. Feel free to test it and see if its fits your needs.

**Comment by NCC1701M** [comment]
You're welcome. Glad, I could help

**Comment by NCC1701M** [comment]
@roroettg I've installed version 10.2.0-RC-3 so far it works but I still have some missing properties and classes which causes errors in my code.

`Blockly.JavaScript`: Is missing. The official blockly typings doesn't include it (and the other generators). In my my PR I've implemented them at https://github.com/roroettg/ngx-blockly/blob/92e3f14d3c790bcb7e7ac0de843db70bceaa6f2c/projects/ngx-blockly/src/blockly.ts#L22552-L22605

`Blockly.Events`: The events missing some important properties which are available at runtime but again not included in the official blockly typings as far as I can see the missing properties are at least:
 - blockId
 - name
 - newValue
 - oldValue
 - newParentId
 - oldParentId
 
In the PR I've added them manually to the __Class of `Blockly.Events` module like for example for `Move__Class`: https://github.com/roroettg/ngx-blockly/blob/92e3f14d3c790bcb7e7ac0de843db70bceaa6f2c/projects/ngx-blockly/src/blockly.ts#L13140-L13142

Would be great if they could be implemented in ngx-blockly as well.

**Comment by roroettg** [comment]
As you mentioned some blockly typings are currently missing, but I hope they will be added in the future or it will be easier in general to access blockly since they are planning to move to typescript in the near future.

I hesitate to integrate an own blockly.ts since we will have to adapt it everytime a new blockly version is released. These missing properties should be made available by blockly itself. 

Never the less there is a workaround, which can be used until then.

**Workaround**:

` Blockly[NgxBlocklyGenerator.JAVASCRIPT]` or `Blockly['JavaScript']` can be used to access the Generators.

This workaround can be used for many properties that are available at runtime. To access properties of an event you could use:

`event['newParentId'].`

**Comment by NCC1701M** [comment]
Yeah you right, blockly should implement it in their typings. I will go with the workaround. But after I've fixed the there are some I couldn't get fixed.

It seems that `NgxToolboxBuilderService` and all the default categories (e.g. `LOGIC_CATEGORY` `LOOP_CATEGORY`, ...) are not found in ngx-blockly. What happend with them? I couldn't find them in the code as well.

**Comment by roroettg** [comment]
Sorry about that. I forgot to extract them from `NgxToolboxBuilderService`. They can be found for now in `category.ts` with RC-4.

**Comment by NCC1701M** [comment]
> 
> 
> Sorry about that. I forgot to extract them from `NgxToolboxBuilderService`. They can be found for now in `category.ts` with RC-4.

And what's about `NgxToolboxBuilderService`? I can't find it in the code as well... Do I have to use Blockly methods?

**Comment by roroettg** [comment]
I really need to get going to update the documentation.  😄 

The idea was to move that to NgxBlocklyToolbox to have more freedom in creating custom toolbox implementations. 

```typescript
        const workspace = new Blockly.WorkspaceSvg(new Blockly.Options({}));
        const toolbox: NgxBlocklyToolbox = new NgxBlocklyToolbox(workspace);
        toolbox.nodes = [
            LOGIC_CATEGORY,
            new Category('bla', '#ff0000', [...this.customBlocks, this.button, this.label]),
            LOOP_CATEGORY,
            MATH_CATEGORY,
            TEXT_CATEGORY,
            LISTS_CATEGORY,
            COLOUR_CATEGORY,
            new Separator(),
            VARIABLES_CATEGORY,
            FUNCTIONS_CATEGORY
        ];
        this.config.toolbox = toolbox.toXML();
```

Unfortunately this has some downsides, since Blocklys Toolbox always needs a workspace (even if it is not the one used later on)

**Comment by NCC1701M** [comment]
Hi @roroettg 

It's me... again...

I've tried to set up the toolbox like you did in the example project. The toolbox is shown and my personal categories are working. But when I click on the default categories I've added I get an error for each clicked category:

grafik

Only the variables category works but not correct. The `Create variable...` is shown and the input dialog opens when I click on it. But created variables are not shown in list. Also when I try to import an existing workspace where I had already created variables an error occurs with the message: `Unkown block type: variables_set`. I guess it is the same reason why no created variables are shown.

My code to create the toolbox:
```typescript
		const workspace = new Blockly.WorkspaceSvg(new Blockly.Options({}));
		const toolbox = new NgxBlocklyToolbox(workspace);

		toolbox.nodes = [
			new MyCategory(),
			new Separator(),
			LOGIC_CATEGORY,
			LOOP_CATEGORY,
			MATH_CATEGORY,
			TEXT_CATEGORY,
			LISTS_CATEGORY,
			VARIABLES_CATEGORY
		];
		this.config.toolbox = toolbox.toXML();
```

**Comment by roroettg** [comment]
Hi @NCC1701,

sorry that I still have not updated the documentation.

For using default blocks, you need to import  them like this `import 'blockly/blocks'; `

Otherwise blockly's integrated blocks wont be initialized. I have tried to come up with a way of dynamically importing them, but I have not found a working solution yet.

**Pull request closed without merging**
